# Generated by Django 5.2.5 on 2026-02-20 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_managertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='votertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
