# Generated by Django 5.2.5 on 2026-02-21 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_votertoken_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managertoken',
            name='is_used',
        ),
        migrations.AddField(
            model_name='managertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='managertoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
